about/urls.py
from django.urls import path

from . import views


app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('new/', views.new_post, name='new_post'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path('404/', views.page_not_found, name='404'),
    path('500/', views.server_error, name='500'),
]

users/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


handler404 = "posts.views.page_not_found" # noqa
handler500 = "posts.views.server_error" # noqa


urlpatterns = [
    path('administrator/', admin.site.urls),
    path('', include('posts.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

about/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название',
                             help_text='Группа, в которой может быть '
                                       'опубликован текст')
    slug = models.SlugField(unique=True)
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст',
                            help_text='Текст публикации')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts')
    group = models.ForeignKey(Group, blank=True, null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts', verbose_name='Группа')
    '''image = models.ImageField(upload_to='posts/', blank=True, null=True,
                              verbose_name='Заглавная картинка')'''

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = ['group', 'text']

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from posts.models import User


class CreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'author.html'


class AboutTechView(TemplateView):
    template_name = 'tech.html'

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User


POSTS_PER_PAGE = 10


def index(request):
    post_list = Post.objects.select_related('group').all()
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'index.html', {'page': page,
                                          'paginator': paginator})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'group.html', {'group': group,
                                          'page': page,
                                          'paginator': paginator})


@login_required
def new_post(request):
    form = PostForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('index')

    return render(request, 'new_post.html', {'form': form,
                                             'edit_mode': False})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'profile.html', {'user_posts': author,
                                            'page': page,
                                            'paginator': paginator})


def post_view(request, username, post_id):
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, id=post_id, author=author)
    return render(request, 'post.html', {'user_posts': post.author,
                                         'post': post})


@login_required
def post_edit(request, username, post_id):
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, id=post_id, author=author)

    if request.user != post.author:
        return redirect('post', username=username, post_id=post_id)

    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return redirect('post', username=request.user.username,
                        post_id=post_id)

    return render(request, 'new_post.html', {'form': form,
                                             'edit_mode': True,
                                             'post': post})


def page_not_found(request, exception):
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=404
    )


def server_error(request):
    return render(request, 'misc/500.html', status=500)

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('signup')
    template_name = 'signup.html'

about/templates/author.html
{% extends "base.html" %}
{% block title %}Об авторе{% endblock %}
{% block header %}Технологии{% endblock %}
{% block content %}
{% load user_filters %}
{% load static %}
  <main role="main" class="container">
      <div class="row">
          <!-- Левый вспомогательный блок -->
          <div class="col-md-3 mb-3 mt-1">
              <div class="card custom_card fixed_div">
                  <div class="card-body">
                      <ul class="list-group list-group-flush">
                          <li class="list-group-item custom_card">
                              <a href="#about_author_topic"><div class="h6 text-muted">Об авторе</div></a>
                              <a href="#our_team_topic"><div class="h6 text-muted">Наша команда</div></a>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
          <!-- Тело страницы -->
          <div class="col-md-9">
              <div class="card-body">
                  <p id="about_author_topic"><h4>Об авторе</h4></p>
                  <div class="card-text">
                      <p>Привет!</p>
                      <p>
                          Меня зовут <b>Олег</b>, я из подмосковного города Королёва.
                      </p>
                      <p>
                          Я профессиональный программист с двумя дипломами, 10.5 годами опыта на C++, очень узкой специализацией и так себе образованием.
                          Я закончил
                          <a href="https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%80%D0%BE%D0%BB%D1%91%D0%B2%D1%81%D0%BA%D0%B8%D0%B9_%D0%BA%D0%BE%D0%BB%D0%BB%D0%B5%D0%B4%D0%B6_%D0%BA%D0%BE%D1%81%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%BE%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BD%D0%B8%D1%8F_%D0%B8_%D1%82%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D0%B8">
                              КККМТ
                          </a>
                          (Королёвский колледж космического машиностроение и технологии) по специальности <b>Программное обеспечение вычислительной техники и автоматизированных систем</b> в 2010 году,
                           а потом
                          <a href="https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D1%81%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9_%D0%BF%D0%BE%D0%BB%D0%B8%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%83%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0%B5%D1%82">
                            МАМИ
                          </a>
                            (Московский государственный машиностроительный университет) в 2015 году, который сейчас почему-то называется политехнический О_о, по той же специальности.
                      </p>
                      <p>
                          С детства нравились всякие автоматизированные и умные штуки, которые сами что-то делают. Так я и попал в программирование.
                      </p>
                      <p>
                          10.5 лет я работаю в Авиационном регистре Российской Федерации и пишу там системы обработки полётной информации для самолётов гражданской авиации (системы расшифровки чёрных ящиков),
                          а так же сопутствующую инфраструктуру: системы хранения информациции в БД, аналитика информации из БД, написал даже интерпретатор для того, чтобы пользователи могли сами реализовывать алгоритмы анализа информации.
                      </p>
                      <p>
                          Специализация довольно нестандартная, инструменты для разработки тоже. Отсутствуют многие понятия из того, что принято в мировой практике. Ну, и много ещё разного рода веселья.
                      </p>
                      <p>
                          Хочется упорядочить знания, понять, как устроены и работают большие интересные проекты, а так же понять, как устроена работа в команде с использованием всех командных средств разработки.
                      </p>
                      <p>
                          Собственно, поэтому я здесь :)
                      </p>
                  </div>
                  <div class="social_wrap">
                      <div class="social">
                          <a href="https://github.com/Fastex007" target="_blank" title="github">
                              <img class="social_image" src="{% static "about/images/github-logo.png" %}" alt="github">
                          </a>
                      </div>
                      <div class="social">
                          <a href="https://hh.ru/resume/80e8d8e3ff082b248e0039ed1f3867324f3537" target="_blank" title="ХХ">
                              <img class="social_image" src="{% static "about/images/hh-logo.png" %}" alt="github">
                          </a>
                      </div>
                      <div class="social">
                          <a href="https://www.instagram.com/fastex007/" target="_blank" title="Instagram">
                              <img class="social_image" src="{% static "about/images/instagram-logo.png" %}" alt="github">
                          </a>
                      </div>
                  </div>
              </div>

              <div class="card-body">
                  <p id="our_team_topic"><h4>Наша команда</h4></p>
                  <div class="team_wrap">

                      <div class="team_member">
                          <div class="team_member_photo">
                              <img class="member_photo" src="{% static "about/images/vasilisa.png" %}">
                          </div>
                          <div class="team_member_description">
                              <div class="member_name">Василиса</div>
                              <div class="member_grade">Project manager</div>
                              <div class="member_description">Самый мудрый и неуклюжий член команды. Стоит ей запрыгнуь на подоконник, как тут же валятся горшки с цветами. Даже в других комнатах.</div>
                          </div>
                      </div>

                      <div class="team_member">
                          <div class="team_member_photo">
                              <img class="member_photo" src="{% static "about/images/djonik.png" %}">
                          </div>
                          <div class="team_member_description">
                              <div class="member_name">Johny D'Lear McGreaf</div>
                              <div class="member_grade">Team lead</div>
                              <div class="member_description">Все время спит и не мешает работать. Всегда готов воремя напомнить, что пора отдохнуть и погулять (с ним).</div>
                          </div>
                      </div>

                      <div class="team_member">
                          <div class="team_member_photo">
                              <img class="member_photo" src="{% static "about/images/tishka.png" %}">
                          </div>
                          <div class="team_member_description">
                              <div class="member_name">Тишка (он же Dandelion)</div>
                              <div class="member_grade">QA engineer</div>
                              <div class="member_description">Теструет нервную систему всего персонала.</div>
                          </div>
                      </div>

                      <div class="team_member">
                          <div class="team_member_photo">
                              <img class="member_photo" src="{% static "about/images/zeliboba.png" %}">
                          </div>
                          <div class="team_member_description">
                              <div class="member_name">Тобиас (Тоба)</div>
                              <div class="member_grade">Middle developer</div>
                              <div class="member_description">Самый мотивированный член команды. За любую движуху, даже за голодовку.</div>
                          </div>
                      </div>

                      <div class="team_member">
                          <div class="team_member_photo">
                              <img class="member_photo" src="{% static "about/images/sheldon_svinina.png" %}">
                          </div>
                          <div class="team_member_description">
                              <div class="member_name">Шелдон (потому что Шелти)</div>
                              <div class="member_grade">Junior developer</div>
                              <div class="member_description">Морская свинина. Пока только ест.</div>
                          </div>
                      </div>

                  </div>
              </div>
          </div>
      </div>
  </main>
{% endblock %}

about/templates/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block header %}Технологии{% endblock %}
{% block content %}
{% load user_filters %}

  <main role="main" class="container">
          <canvas id="projector"></canvas>
    {% load static %}
    <script  src="{% static "about/js/login_bg_script.js" %}"></script>
      <div class="row">
          <!-- Левый вспомогательный блок -->
          <div class="col-md-3 mb-3 mt-1">
              <div class="card custom_card fixed_div">
                  <div class="card-body">
                      <ul class="list-group list-group-flush">
                          <li class="list-group-item custom_card">
                              <a href="#python_topic"><div class="h6 text-muted">Python</div></a>
                              <a href="#django_topic"><div class="h6 text-muted">Django</div></a>
                              <a href="#sqlite_topic"><div class="h6 text-muted">SQLite</div></a>
                              <a href="#js_topic"><div class="h6 text-muted">JavaScript</div></a>
                              <a href="#bootstrap_topic"><div class="h6 text-muted">Bootstrap</div></a>
                              <a href="#html5_topic"><div class="h6 text-muted">HTML 5</div></a>
                              <a href="#css3_topic"><div class="h6 text-muted">CSS 3</div></a>
                              <a href="#git_topic"><div class="h6 text-muted">GIT</div></a>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
          <!-- Тело страницы -->
          <div class="col-md-9">
              <div class="card-body">
                  <p id="python_topic"><h4>Python</h4></p>
                  <div class="tech-image">
                      <img class="card-image" src="{% static "about/images/python_logo.png" %}">
                  </div>
                  <div class="card-text tech-image">
                        Высокоуровневый язык программирования общего назначения, ориентированный на повышение производительности разработчика и читаемости кода. Синтаксис ядра Python минималистичен. В то же время стандартная библиотека включает большой набор полезных функций.
                    </div>
              </div>
              <div class="card-body">
                  <p id="django_topic"><h4>Django</h4></p>
                  <div class="tech-image">
                      <img class="card-image" src="{% static "about/images/django-logo.png" %}">
                  </div>
                  <div class="card-text tech-image">
                        Свободный фреймворк для веб-приложений на языке Python, использующий шаблон проектирования MVC. Проект поддерживается организацией Django Software Foundation.
                        Сайт на Django строится из одного или нескольких приложений, которые рекомендуется делать отчуждаемыми и подключаемыми. Это одно из существенных архитектурных отличий этого фреймворка от некоторых других (например, Ruby on Rails). Один из основных принципов фреймворка — DRY (англ. Don't repeat yourself)
                        Также, в отличие от других фреймворков, обработчики URL в Django конфигурируются явно при помощи регулярных выражений.
                        Для работы с базой данных Django использует собственный ORM, в котором модель данных описывается классами Python, и по ней генерируется схема базы данных.
                    </div>
              </div>
              <div class="card-body">
                  <p id="sqlite_topic"><h4>SQLite</h4></p>
                  <div class="tech-image">
                      <img class="card-image" src="{% static "about/images/sqlite-logo.png" %}">
                  </div>
                  <div class="card-text tech-image">
                        Компактная встраиваемая СУБД. Исходный код библиотеки передан в общественное достояние. В 2005 году проект получил награду Google-O’Reilly Open Source Awards
                    </div>
              </div>
              <div class="card-body">
                  <p id="js_topic"><h4>JavaScript</h4></p>
                  <div class="tech-image">
                      <img class="card-image" src="{% static "about/images/js-logo.png" %}">
                  </div>
                  <div class="card-text tech-image">
                        Мультипарадигменный язык программирования. Поддерживает объектно-ориентированный, императивный и функциональный стили. Является реализацией стандарта ECMAScript (стандарт ECMA-262).
                        JavaScript обычно используется как встраиваемый язык для программного доступа к объектам приложений. Наиболее широкое применение находит в браузерах как язык сценариев для придания интерактивности веб-страницам.
                    </div>
              </div>
              <div class="card-body">
                  <p id="bootstrap_topic"><h4>Bootstrap</h4></p>
                  <div class="tech-image">
                      <img class="card-image" src="{% static "about/images/bootstrap-logo.png" %}">
                  </div>
                  <div class="card-text tech-image">
                        Свободный набор инструментов для создания сайтов и веб-приложений. Включает в себя HTML- и CSS-шаблоны оформления для типографики, веб-форм, кнопок, меток, блоков навигации и прочих компонентов веб-интерфейса, включая JavaScript-расширения.
                        Bootstrap использует современные наработки в области CSS и HTML, поэтому необходимо быть внимательным при поддержке старых браузеров.
                    </div>
              </div>
              <div class="card-body">
                  <p id="html5_topic"><h4>HTML 5</h4></p>
                  <div class="tech-image">
                      <img class="card-image" src="{% static "about/images/html5-logo.png" %}">
                  </div>
                  <div class="card-text tech-image">
                         язык для структурирования и представления содержимого всемирной паутины. Это пятая версия HTML. Хотя стандарт был завершён (рекомендованная версия к использованию) только в 2014 году (предыдущая, четвёртая, версия опубликована в 1999 году), уже с 2013 года браузерами оперативно осуществлялась поддержка, а разработчиками — использование рабочего стандарта (англ. HTML Living Standard). Цель разработки HTML5 — улучшение уровня поддержки мультимедиа-технологий с одновременным сохранением обратной совместимости, удобочитаемости кода для человека и простоты анализа для парсеров.
                    </div>
              </div>
              <div class="card-body">
                  <p id="css3_topic"><h4>CSS 3</h4></p>
                  <div class="tech-image">
                      <img class="card-image" src="{% static "about/images/css3-logo.png" %}">
                  </div>
                  <div class="card-text tech-image">
                         Формальный язык описания внешнего вида документа (веб-страницы), написанного с использованием языка разметки (чаще всего HTML или XHTML). Также может применяться к любым XML-документам, например, к SVG или XUL.
                    </div>
              </div>
              <div class="card-body">
                  <p id="git_topic"><h4>GIT</h4></p>
                  <div class="tech-image">
                      <img class="card-image" src="{% static "about/images/git-logo.png" %}">
                  </div>
                  <div class="card-text tech-image">
                         Распределённая система управления версиями. Проект был создан Линусом Торвальдсом для управления разработкой ядра Linux, первая версия выпущена 7 апреля 2005 года. На сегодняшний день его поддерживает Джунио Хамано.
                    </div>
              </div>
          </div>
      </div>
  </main>
{% endblock %}

posts/templates/new_post.html
{% extends "base.html" %}
{% block title %}{% if edit_mode %}Редактирование поста #{{ post.id }}{% else %}Новая запись | {{ user.username }}{% endif %}{% endblock %}
{% block header %}{% if edit_mode %}Редактирование поста #{{ post.id }}{% else %}Новая запись | {{ user.username }}{% endif %}{% endblock %}
{% block content %}
{% load user_filters %}

<!--Можно же было как-то проще ?))-->
{% load custom_template_tags %}
{% if edit_mode %}
    {% set mode_text = "Редактировать" %}
    {% url 'post_edit' post.author.username post.id  as form_action_url %}
{% else %}
    {% set mode_text = "Новая" %}
    {% url 'new_post' as form_action_url %}
{% endif %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{{ mode_text }} запись</div>
                <div class="card-body">
                    {% if form.errors %}
                        <ol>
                        {% for error in form.errors %}
                            <li><strong>{{ error|escape }}</strong></li>
                        {% endfor %}
                        </ol>
                    {% endif %}

                    <form action="{{ form_action_url }}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                    <div class="col-md-6">
                                        {{ field|addclass:"form-control" }}
                                        {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                        {% endif %}
                                    </div>
                            </div>
                        {% endfor %}

                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                <div class="card-header">{{ mode_text }} запись</div>
                            </button>
                        </div>
                    </form>
                </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

posts/templates/post.html
{% extends "base.html" %}
{% block title %}Запись #{{ post.id }} | {{ user_posts.get_full_name }}{% endblock %}
{% block header %}Запись #{{ post.id }} | {{ user_posts.get_full_name }}{% endblock %}
{% block content %}
    <main role="main" class="container">
        <div class="row">
            {% include 'includes/author_info.html' %}
            <div class="col-md-9">
                <div class="card mb-3 mt-1 shadow-sm">
                    {% include 'includes/post_info.html' %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

posts/templates/profile.html
{% extends "base.html" %}
{% block title %}Записи пользователя {{ user_posts.get_full_name }}{% endblock %}
{% block header %}Записи пользователя {{ user_posts.get_full_name }}{% endblock %}
{% block content %}
    <main role="main" class="container">
        <div class="row">
            {% include 'includes/author_info.html' %}
            <div class="col-md-9">
                {% for post in page %}
                    <div class="card mb-3 mt-1 shadow-sm">
                        {% include 'includes/post_info.html' %}
                    </div>
                {% empty %}
                    У пользователя {{ user_posts.get_full_name }} нет записей
                {% endfor %}
                {% include 'includes/paginator.html' with item=page paginator=paginator %}
            </div>
        </div>
    </main>
{% endblock %}

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>

    {% url 'about:tech' as about_tech_url %}
    {% if request.path == about_tech_url %}
        <link rel="stylesheet" type="text/css" href="{% static "about/css/tech_style.css" %}">
        <script src="{% static "about/js/jquery-1.10.1.min.js" %}"></script>
        <link rel="stylesheet" href="{% static "about/css/normalize.min.css" %}">
        <script src="{% static "about/js/easeljs-0.7.1.min.js" %}"></script>
        <script src="{% static "about/js/TweenMax.min.js" %}"></script>
    {% endif %}

    {% url 'about:author' as about_author_url %}
    {% if request.path == about_author_url %}
        <link rel="stylesheet" type="text/css" href="{% static "about/css/author_style.css" %}">
    {% endif %}
</head>

<body>
    {% include 'includes/nav.html' %}
        <main>
            <div class="container">
                <h1>{% block header %}The Last Social Media You'll Ever Need{% endblock %}</h1>
                {% block content %}
                <!-- Содержимое страницы -->
                {% endblock %}
            </div>
        </main>
    {% include 'includes/footer.html' %}
</body>

</html>

templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
    <p>
        {{ group.description }}
    </p>
    {% for post in page %}
        <h3>
            Автор: {{ post.author.get_full_name }}, Дата публикации: {{ post.pub_date|date:"d M Y" }}
        </h3>
        {% include 'includes/head_image.html' %}
        <p>
            {{ post.text|linebreaksbr }}
        </p>
        <hr>
    {% endfor %}

    {% include 'includes/paginator.html' with item=page paginator=paginator %}

{% endblock %}

templates/includes/author_info.html
<div class="col-md-3 mb-3 mt-1">
    <div class="card">
        <div class="card-body">
            <div class="h2">
                {{ user_posts.get_full_name }}
            </div>
            <div class="h3 text-muted">
                 @{{ user_posts.username }}
            </div>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="h6 text-muted">
                Подписчиков: XXX <br />
                Подписан: XXX
                </div>
            </li>
            <li class="list-group-item">
                <div class="h6 text-muted">
                    Записей: {{ user_posts.posts.count }}
                </div>
            </li>
        </ul>
    </div>
</div>

templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a> -
        <a href="{% url 'about:tech' %}">Технологии</a>
    </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube</p>
</footer>

templates/includes/head_image.html
{% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img" src="{{ im.url }}">
    {% endthumbnail %}